pipeline {
    agent {
        docker {
            image 'node:14' // Base Docker image to use for Node.js
            label 'docker-agent' // Docker agent label
            registryUrl 'https://index.docker.io/v1/' // Default Docker Hub URL
            registryCredentialsId 'docker-account' // Jenkins credentials ID for Docker Hub
        }
    }

    environment {
        IMAGE_NAME = 'locoioioi/cosc2767-rmit-store-client' // Docker image name
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/locoioioi/COSC2767-RMIT-Store'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('client') {
                    sh 'npm ci'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('client') {
                    sh 'npm run build'
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    def customImage = docker.build("${IMAGE_NAME}:latest", "client") 

                    // Push the image to the Docker registry
                    customImage.push()
                }
            }
        }
    }

    post {
        success {
            echo 'React.js build and Docker image push completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs for more details.'
        }
    }
}
