pipeline {
    agent any
    tools {
        nodejs "Node"
        dockerTool 'Docker'
    }

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('docker-account') // Jenkins credential ID for Docker Hub
        IMAGE_NAME = 'locoioioi/cosc2767-rmit-store-client' // Docker image name
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/locoioioi/COSC2767-RMIT-Store'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('client') {
                    sh 'npm ci'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('client') {
                    sh 'npm run build'
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'client/dist/**/*', allowEmptyArchive: false
            }
        }

        stage("Test Docker") {
            steps {
                sh 'docker --version'
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                dir('client') {
                    script {
                        // Build the Docker image
                        docker.build("${IMAGE_NAME}:latest")
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'React.js build and Docker image push completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs for more details.'
        }
    }
}
