version: "3.9"

services:
    db:
        container_name: db
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - data:/data/db

    frontend:
        container_name: frontend
        build:
            context: ./client
            dockerfile: dockerfile
        ports:
            - "8080:80"
        environment:
            - API_URL=http://backend:3000/api
        depends_on:
            - backend

    backend:
        container_name: backend
        build:
            context: ./server
            dockerfile: dockerfile
        ports:
            - "3000:3000"
        environment:
            - MONGO_URI=mongodb://db:27017/rmit_store
            - CLIENT_URL=http://frontend:8080
        depends_on:
            - db

volumes:
    data:
